[package]
name = "gdaxconnection"
version = "0.1.0"
authors = ["root"]

[dependencies]
websocket = "0.17.1"
openssl = "0.7.6"
url = { git = "https://github.com/servo/rust-url" }
lazy_static = "0.2.1"
regex = "0.1"
